name: Composite Action for Testing
description: testing custom action
runs:
  using: 'composite'
  steps:
    - name: Run Action
      uses: __CUSTOM_ACTION_REPO__@main
      id: sample
      with:
        milliseconds: 130000
    - name: Test Outputs
      run: |
        if ("${{ steps.sample.outputs.Mongocontainer }}") {
          Write-Output "Output Value Found [${{ steps.sample.outputs.Mongocontainer }}]"
        } else {
          Write-Error "No output value found"
          exit 1
        }
      shell: pwsh
